# Prepend variables to script file
set(SCRIPT_HEADER "#!/bin/bash
PROGRAM_NAME=\"${PROGRAM_NAME}\"
PROGRAM_VERSION=\"${PROGRAM_VERSION}\"
DAEMON_NAME=\"${DAEMON_NAME}\"
CLI_NAME=\"${CLI_NAME}\"
UNINSTALLER_NAME=\"${UNINSTALLER_NAME}\"
SERVICE_NAME=\"${SERVICE_NAME}\"
DEPS=\"${DEPS}\"
")

function(prepend_script_header FILE_PATH)
  file(READ "${FILE_PATH}" SCRIPT_CONTENT)
  file(WRITE "${FILE_PATH}" "${SCRIPT_HEADER}\n${SCRIPT_CONTENT}")
endfunction()
prepend_script_header("${MAKESELF_OUTPUT_DIR}/install.sh")
prepend_script_header("${MAKESELF_OUTPUT_DIR}/${UNINSTALLER_NAME}")

# Substitute variables in .service file
file(READ "${MAKESELF_OUTPUT_DIR}/${SERVICE_NAME}.service" SERVICE_FILE_CONTENT)
string(REPLACE "<PROGRAM_NAME>" "${PROGRAM_NAME}" SERVICE_FILE_CONTENT "${SERVICE_FILE_CONTENT}")
string(REPLACE "<SERVICE_NAME>" "${SERVICE_NAME}" SERVICE_FILE_CONTENT "${SERVICE_FILE_CONTENT}")
string(REPLACE "<DAEMON_NAME>" "${DAEMON_NAME}" SERVICE_FILE_CONTENT "${SERVICE_FILE_CONTENT}")
file(WRITE "${MAKESELF_OUTPUT_DIR}/${SERVICE_NAME}.service" "${SERVICE_FILE_CONTENT}")
